### ISSUE TITLE
Support style in Expandable

### ISSUE THREAD

**Issue by stoyle** [fabric-ds/react#97]
The props of Expandable says it support a style prop, however I cannot see it is actually added anywhere. Also checked the sources, but I might of course be wrong.

It would help us quite a bit to handle custom styling. However, the way our component was designed we need to target the inner button and span, and that may not what this style prop was intended for?

Anyways, our styling targets a surrounding div, targeted by css modules, and we have overriden styles the following way. If there is a way to prevent this, that would of course be awesome.

```css
.expandArea div button {
    display: flex;
    align-items: center;
}

.expandArea div button span {
    font-weight: normal;
    margin-right: 18px;
    hyphens: manual;
    overflow-wrap: break-word;
    display: inline-block;
}

.expandArea div button:focus,
.expandArea div button:hover {
    text-decoration: none;
}
```

Will be happy to provide a PR if you give me a direction for how to fix this.
